
package introsde.dsantoro.storagews;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import introsde.dsantoro.dbws.Activity;
import introsde.dsantoro.dbws.Goal;
import introsde.dsantoro.dbws.Meal;
import introsde.dsantoro.dbws.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Storagews", targetNamespace = "http://storagews.dsantoro.introsde/")
@XmlSeeAlso({
    introsde.dsantoro.dbws.ObjectFactory.class,
    introsde.dsantoro.storagews.ObjectFactory.class
})
public interface Storagews {


    /**
     * 
     * @param personId
     * @return
     *     returns introsde.dsantoro.dbws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadPersonResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/readPersonRequest", output = "http://storagews.dsantoro.introsde/Storagews/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.dsantoro.dbws.Activity>
     */
    @WebMethod
    @WebResult(name = "activity", targetNamespace = "")
    @RequestWrapper(localName = "readActivityList", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadActivityList")
    @ResponseWrapper(localName = "readActivityListResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadActivityListResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/readActivityListRequest", output = "http://storagews.dsantoro.introsde/Storagews/readActivityListResponse")
    public List<Activity> readActivityList();

    /**
     * 
     * @param person
     * @param activityRqst
     * @return
     *     returns introsde.dsantoro.dbws.Activity
     */
    @WebMethod
    @WebResult(name = "activity", targetNamespace = "")
    @RequestWrapper(localName = "createActivity", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.CreateActivity")
    @ResponseWrapper(localName = "createActivityResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.CreateActivityResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/createActivityRequest", output = "http://storagews.dsantoro.introsde/Storagews/createActivityResponse")
    public Activity createActivity(
        @WebParam(name = "activityRqst", targetNamespace = "")
        Activity activityRqst,
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param goalId
     * @return
     *     returns introsde.dsantoro.dbws.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "readGoal", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadGoal")
    @ResponseWrapper(localName = "readGoalResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadGoalResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/readGoalRequest", output = "http://storagews.dsantoro.introsde/Storagews/readGoalResponse")
    public Goal readGoal(
        @WebParam(name = "goalId", targetNamespace = "")
        Long goalId);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.dsantoro.dbws.Goal>
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "readGoalList", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadGoalList")
    @ResponseWrapper(localName = "readGoalListResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadGoalListResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/readGoalListRequest", output = "http://storagews.dsantoro.introsde/Storagews/readGoalListResponse")
    public List<Goal> readGoalList();

    /**
     * 
     * @param person
     * @param goalRqst
     * @return
     *     returns introsde.dsantoro.dbws.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "createGoal", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.CreateGoal")
    @ResponseWrapper(localName = "createGoalResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.CreateGoalResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/createGoalRequest", output = "http://storagews.dsantoro.introsde/Storagews/createGoalResponse")
    public Goal createGoal(
        @WebParam(name = "goalRqst", targetNamespace = "")
        Goal goalRqst,
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.dsantoro.dbws.Person>
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadPersonListResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/readPersonListRequest", output = "http://storagews.dsantoro.introsde/Storagews/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param personRqst
     * @return
     *     returns introsde.dsantoro.dbws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.CreatePersonResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/createPersonRequest", output = "http://storagews.dsantoro.introsde/Storagews/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "personRqst", targetNamespace = "")
        Person personRqst);

    /**
     * 
     * @param mealId
     * @return
     *     returns introsde.dsantoro.dbws.Meal
     */
    @WebMethod
    @WebResult(name = "meal", targetNamespace = "")
    @RequestWrapper(localName = "readMeal", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadMeal")
    @ResponseWrapper(localName = "readMealResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadMealResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/readMealRequest", output = "http://storagews.dsantoro.introsde/Storagews/readMealResponse")
    public Meal readMeal(
        @WebParam(name = "mealId", targetNamespace = "")
        Long mealId);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.dsantoro.dbws.Meal>
     */
    @WebMethod
    @WebResult(name = "meal", targetNamespace = "")
    @RequestWrapper(localName = "readMealList", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadMealList")
    @ResponseWrapper(localName = "readMealListResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadMealListResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/readMealListRequest", output = "http://storagews.dsantoro.introsde/Storagews/readMealListResponse")
    public List<Meal> readMealList();

    /**
     * 
     * @param person
     * @param mealRqst
     * @return
     *     returns introsde.dsantoro.dbws.Meal
     */
    @WebMethod
    @WebResult(name = "meal", targetNamespace = "")
    @RequestWrapper(localName = "createMeal", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.CreateMeal")
    @ResponseWrapper(localName = "createMealResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.CreateMealResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/createMealRequest", output = "http://storagews.dsantoro.introsde/Storagews/createMealResponse")
    public Meal createMeal(
        @WebParam(name = "mealRqst", targetNamespace = "")
        Meal mealRqst,
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param activityId
     * @return
     *     returns introsde.dsantoro.dbws.Activity
     */
    @WebMethod
    @WebResult(name = "activity", targetNamespace = "")
    @RequestWrapper(localName = "readActivity", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadActivity")
    @ResponseWrapper(localName = "readActivityResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.ReadActivityResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/readActivityRequest", output = "http://storagews.dsantoro.introsde/Storagews/readActivityResponse")
    public Activity readActivity(
        @WebParam(name = "activityId", targetNamespace = "")
        Long activityId);

    /**
     * 
     * @param quantity
     * @param start
     * @param searchKey
     * @return
     *     returns java.util.List<introsde.dsantoro.dbws.Meal>
     */
    @WebMethod
    @WebResult(name = "meal", targetNamespace = "")
    @RequestWrapper(localName = "searchMeals", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.SearchMeals")
    @ResponseWrapper(localName = "searchMealsResponse", targetNamespace = "http://storagews.dsantoro.introsde/", className = "introsde.dsantoro.storagews.SearchMealsResponse")
    @Action(input = "http://storagews.dsantoro.introsde/Storagews/searchMealsRequest", output = "http://storagews.dsantoro.introsde/Storagews/searchMealsResponse")
    public List<Meal> searchMeals(
        @WebParam(name = "searchKey", targetNamespace = "")
        String searchKey,
        @WebParam(name = "start", targetNamespace = "")
        int start,
        @WebParam(name = "quantity", targetNamespace = "")
        int quantity);

}
