
package introsde.dsantoro.storagews;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "storagewsService", targetNamespace = "http://storagews.dsantoro.introsde/", wsdlLocation = "http://192.168.5.3:6903/ws/storagews?wsdl")
public class StoragewsService
    extends Service
{

    private final static URL STORAGEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException STORAGEWSSERVICE_EXCEPTION;
    private final static QName STORAGEWSSERVICE_QNAME = new QName("http://storagews.dsantoro.introsde/", "storagewsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.5.3:6903/ws/storagews?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STORAGEWSSERVICE_WSDL_LOCATION = url;
        STORAGEWSSERVICE_EXCEPTION = e;
    }

    public StoragewsService() {
        super(__getWsdlLocation(), STORAGEWSSERVICE_QNAME);
    }

    public StoragewsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STORAGEWSSERVICE_QNAME, features);
    }

    public StoragewsService(URL wsdlLocation) {
        super(wsdlLocation, STORAGEWSSERVICE_QNAME);
    }

    public StoragewsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STORAGEWSSERVICE_QNAME, features);
    }

    public StoragewsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StoragewsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Storagews
     */
    @WebEndpoint(name = "StoragewsImplPort")
    public Storagews getStoragewsImplPort() {
        return super.getPort(new QName("http://storagews.dsantoro.introsde/", "StoragewsImplPort"), Storagews.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Storagews
     */
    @WebEndpoint(name = "StoragewsImplPort")
    public Storagews getStoragewsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://storagews.dsantoro.introsde/", "StoragewsImplPort"), Storagews.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STORAGEWSSERVICE_EXCEPTION!= null) {
            throw STORAGEWSSERVICE_EXCEPTION;
        }
        return STORAGEWSSERVICE_WSDL_LOCATION;
    }

}
